name: Valida imagem docker

on: [pull_request]

jobs:
  build:
    environment: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dockerfile lint check
      run: docker run --rm -i hadolint/hadolint < Dockerfile
   
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/darckfast/brasilapi
        tag-sha: true

    - name: Login to Github packages  
      uses: docker/login-action@v1.3.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_PAT }}
        
    - name: Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master    

    - name: Build da imagem docker
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: 
       # - ${{ steps.docker_meta.outputs.tags }}
        - ghcr.io/darckfast/brasilapi:pr_${{ github.event.number }}
        labels: ${{ steps.docker_meta.outputs.labels }}

   #- name: Rodar testes na imagem docker
   #   run: docker run -d --name brasilapi -p 3000:3000 --rm ghcr.io/darckfast/brasilapi:pull_request && npm i && npm run test:docker

    #- name: Digest da imagem
    #  run: echo ${{ steps.docker_build.outputs.digest }}

    - uses: homoluctus/gitrivy@v1.0.0
      with:
        #cache-from: type=local,src=/tmp/.buildx-cache
        token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/darckfast/brasilapi:${{ steps.docker_meta.outputs.tags[0] }}
